### ISSUE TITLE
How do I hang bullet points? 

### ISSUE THREAD

**Issue by chipotlecornsalsa** [chipotlecornsalsa/chipotlecornsalsa.github.io#1]

**Comment by saulbaizman** [comment]
Use a negative margin value. Example:

`ul li {
margin-left: -20;
}`

**Comment by chipotlecornsalsa** [comment]
I'm trying to fix how the sentences continue under the bullet points, but I don't know how to push the text to the right. 

<img width="341" alt="screen shot 2018-12-06 at 6 35 32 pm" src="https://user-images.githubusercontent.com/43072871/49618462-b1e04900-f986-11e8-9ac6-926b8267bdb6.png">

**Comment by saulbaizman** [comment]
Are your list items inside a `<ul>` tag? They ought to nested in one like so:
```
<ul>
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ul>
```

**Comment by chipotlecornsalsa** [comment]
That solved everything! Thanks, Saul!
